# Autogenerated wrapper script for FlowCutterPACE17_jll for i686-linux-gnu-cxx03
export flow_cutter_pace17

JLLWrappers.@generate_wrapper_header("FlowCutterPACE17")
JLLWrappers.@declare_executable_product(flow_cutter_pace17)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        flow_cutter_pace17,
        "bin/flow_cutter_pace17",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
